# config/routes.yaml

route_consultation:
  path: /consultation/
  controller: App\Controller\ConsultationController::index
route_medecin:
  path: /medecin/
  controller: App\Controller\MedecinController::index
route_patient:
  path: /patient/
  controller: App\Controller\PatientController::index
route_medicament:
  path: /medicament/
  controller: App\Controller\MedicamentController::index
app_logout:
  path: /logout
  methods: GET
index:
  path: /
  controller: App\Controller\DefaultController::index